format_version: 11
pipelines:
  build_and_publish_image:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      git-8b31324:
        git: https://github.com/piyawattop/test-scala
        username: piyawattop@hotmail.com
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:J35YTqnKLfjG3oOjAod7tw==:VSMJlR4uUfz+RsZxRC0REjGY4MyuhGu0thXMZj4dbtY4a7k+RR/iBZ1tulGAM3kV
    stages:
    - build_and_publish_image:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build_image:
            timeout: 0
            artifacts:
            - external:
              id: scala-test
              store_id: dockerhub
              configuration:
                options:
                  Image: piyawattop/scala-test
                  Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                - -c
                - docker build -t piyawattop/scala-test:$GO_PIPELINE_LABEL . -f Dockerfile.application
                command: /bin/bash
                run_if: passed